### ISSUE TITLE
Add Badge to Your Profile

### ISSUE THREAD

**Issue by projjal1** [BaseMax/BaseMax#1]
https://github-readme-stats.vercel.app/api?username=BaseMax&&show_icons=true&theme=tokyonight 
Add this at the end of your readme.md file to make your profile more appealing.

**Comment by BaseMax** [comment]
Hi Projjal,

Thank you for your suggest, I added.
It's **A++** account.

Regards,

**Comment by BaseMax** [comment]
I appreciate you.
Thanks,
