### ISSUE TITLE
Add GitHub stats on your profile

### ISSUE THREAD

**Issue by sanchitvj** [BaseMax/BaseMax#2]
![](https://github-readme-stats.vercel.app/api?username=sanchitvj&show_icons=true&title_color=E88795&icon_color=FF33FF&text_color=D6BCD5&bg_color=151515)

**Comment by BaseMax** [comment]
Hi Sanchit,

Thank you for your suggest, I added.
It's **A++** account.

Regards,

**Comment by sanchitvj** [comment]
> Hi Sanchit,
> 
> Thank you for your suggest, I added.
> It's **A++** account.
> 
> Regards,

**Comment by sanchitvj** [comment]
Now your profile looks 10x awesome. Happy to help
