### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by non-descriptive** [BaseMax/BaseMax#6]
> I not hired 

should be 
>I **am** not hired

**Comment by BaseMax** [comment]
Hey Dmitry,

Sir, Can i know about you a bit more?

Thank you very much for your friendly help.
I appreciate you. @non-descriptive 

Cheers,

**Comment by BaseMax** [comment]
Sorry for my typo problem.
Thanks for reporting it, fixed.

**Comment by non-descriptive** [comment]
> i know about you a bit more?

what exactly do you want to know?

**Comment by BaseMax** [comment]
Thankful. I was just a little curious.
I was happy to talk to you.
